title: Ziting (Wilson) He
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wilsonhe029.github.io

aux_links:
  # Template Repository: https://github.com/wilsonhe029/wilson029.github.io
  # Dark Mode: https://wilsonhe029.github.io/#
  
search_enabled: false
color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red