title: Ziting (Wilson) He
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wilsonhe029.github.io

aux_links:
  Template Repository: https://github.com/wilsonhe029/wilson029.github.io
